# Generated by Django 4.2.4 on 2023-08-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem', '0002_alter_marca_options_veiculo_acessorios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='imagem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
