# Generated by Django 4.1.7 on 2023-08-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0011_alter_marca_options_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo'},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='garagem.modelo'),
            preserve_default=False,
        ),
    ]
